### ISSUE TITLE
 Minecraft process finished unexpectedly. There was an error with Malmo.

### ISSUE THREAD

**Issue by satyamedh** [kimbring2/MineRL#3]
@kimbring2, this is the first issue, can you help me, I am not participating in the contest or anything, just want to try it

error:
```
    :deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.util.zip.ZipException: invalid stored block lengths

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --deb

BUILD FAILED

Total time: 20.23 secs


Minecraft process finished unexpectedly. There was an error with Malmo.
```

thanks

**Comment by satyamedh** [comment]
ps: minecraft launches, but still the same error

**Comment by kimbring2** [comment]
@satyamedh Hi, Satyamedh

Utility is one of subfolder of competitiion dependent code at https://github.com/minerllabs/competition_submission_starter_template?files=1. Actually, that code not related directly with a algorithm itself because it was needed for only competition. 

Thank you,
From Dohyeong

**Comment by kimbring2** [comment]
@satyamedh 

Try to run simple test code instead of my little complex one at first for checking what is making Malmo error.

I recommed one at http://minerl.io/docs/environments/index.html#minerlnavigatedense-v0. 

If you have same error after run it, please show a error message for me.

**Comment by satyamedh** [comment]
i am using a conda virtualenv @kimbring2 , it works outside the virtual env, Minecraft starts, but Malmo has a error, I guess it is jdk error, reinstalling it now

**Comment by satyamedh** [comment]
@kimbring2, i have reinstalled java and it solved the previous error, but now I have this error:
```
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\ops\array_grad.py:425: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\ops\gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\logger.py:30: UserWarning: ←[33mWARN: Box bound precision lowered by casting to float32←[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\ops\array_grad.py:425: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\tensorflow\python\ops\gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\logger.py:30: UserWarning: ←[33mWARN: Box bound precision lowered by casting to float32←[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "run1.py", line 115, in <module>
    env = gym.make(env_name)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\envs\registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\envs\registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\envs\registration.py", line 59, in make
    env = cls(**_kwargs)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\core.py", line 133, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\core.py", line 155, in _get_new_instance
    instance.launch()
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\malmo.py", line 477, in launch
    raise EOFError(error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: Access is denied.
java.io.FileNotFoundException: C:\ProgramData\Anaconda3\envs\minerl1\Lib\site-packages\minerl\env\Malmo\Minecraft\.gradle\gradle.log (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.google.common.io.Files.newWriter(Files.java:103)
        at net.minecraftforge.gradle.util.FileLogListenner.<init>(FileLogListenner.java:54)
        at net.minecraftforge.gradle.common.BasePlugin.apply(BasePlugin.java:138)
        at net.minecraftforge.gradle.common.BasePlugin.apply(BasePlugin.java:92)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at build_1amxhb0x2hrajz5w2z1z0pcnq.run(C:\ProgramData\Anaconda3\envs\minerl1\Lib\site-packages\minerl\env\Malmo\Minecraft\build.gradle:27)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.org.gradle.internal.event.ListenerNotificationException: Failed to notify standard output listener.org.gradle.internal.event.ListenerNotificationException: Failed to notify standard output listener.
org.gradle.internal.event.ListenerNotificationException: Failed to notify standard output listener.
org.gradle.internal.event.ListenerNotificationException: Failed to notify standard output listener.
FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify standard output listener.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


Minecraft process finished unexpectedly. There was an error with Malmo.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\pymine\run1.py", line 115, in <module>
    env = gym.make(env_name)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\envs\registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\envs\registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\gym\envs\registration.py", line 59, in make
    env = cls(**_kwargs)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\core.py", line 133, in __init__
    self.instance = self._get_new_instance(port)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\core.py", line 155, in _get_new_instance
    instance.launch()
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\malmo.py", line 453, in launch
    parent_pid, self.minecraft_process.pid, self.host, port, self.instance_dir)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\site-packages\minerl\env\malmo.py", line 669, in _launch_process_watcher
    p.start()
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Anaconda3\envs\minerl1\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by satyamedh** [comment]
this time minecraft didn't start

**Comment by kimbring2** [comment]
@satyamedh Hmm, there is still problem related with Malmo. But, installation manual say that jdk8 is needed(http://minerl.io/docs/tutorials/index.html)

 Let's try it.

**Comment by satyamedh** [comment]
i REinstalled jdk, not UNinstalled, jdk is still there except it is downgraded to jdk8_231.

**Comment by satyamedh** [comment]
ok, i made the virualevn in command prompt running as admin, and `java.io.FileNotFoundException: C:\ProgramData\Anaconda3\envs\minerl1\Lib\site-packages\minerl\env\Malmo\Minecraft\.gradle\gradle.log (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)` was the error, so I restarted the cmd with admin prevliges and it worked , but back to the old error @kimbring2. but with a different stacktrace:\
```
:deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.io.EOFException: Unexpected end of ZLIB input stream

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 26.425 secs

```

**Comment by kimbring2** [comment]
@satyamedh I find one solution at Malmo Github. Here is a link : https://github.com/microsoft/malmo/issues/172. 

Try it,
From Dohyeong

**Comment by satyamedh** [comment]
@kimbring2 , NOW I GET :deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.util.zip.ZipException: invalid CEN header (bad signature)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.128 secs

**Comment by kimbring2** [comment]
@satyamedh 

Can you check a bash file for lauching Minecraft of Malmo? 

https://github.com/microsoft/malmo/blob/master/Minecraft/launchClient.sh

I think we should check a basic process of it.

**Comment by satyamedh** [comment]
@kimbring2 , it launches, guess it is a problem with conda virtualenv

thanks, I'll let you know if it works

**Comment by kimbring2** [comment]
@satyamedh Ok, I wish it works well

**Comment by satyamedh** [comment]
@kimbring2 , still 
```python
:deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 21.183 secs


Minecraft process finished unexpectedly. There was an error with Malmo.
```

**Comment by kimbring2** [comment]
@satyamedh Hi,

I find one solution at https://github.com/Microsoft/malmo/wiki/Troubleshooting.
Can you check it?

![1234](https://user-images.githubusercontent.com/11064407/80562309-53f04d80-8a22-11ea-89c5-5aae114373c7.PNG)

From Dohyeong

**Comment by satyamedh** [comment]
@kimbring2 , i tried that long time ago, before opening this issue. though I am running the train.py without issues, it only happens in the Jupiter notebook

**Comment by satyamedh** [comment]
@kimbring2

**Comment by kimbring2** [comment]
@satyamedh Can you run MineRL now? or still have problem?

**Comment by satyamedh** [comment]
I have
still the same

**Comment by satyamedh** [comment]
@kimbring2

**Comment by kimbring2** [comment]
@satyamedh Hmm, it looks better idea you try it at another computer. It is only way for checking problem.

**Comment by satyamedh** [comment]
@kimbring2 , I even tried in gcloud VM(cuz I don't have any other PC at the moment)
??

**Comment by satyamedh** [comment]
@kimbring2

**Comment by kimbring2** [comment]
@kimbring2 In gcloud, was it working well?

**Comment by satyamedh** [comment]
yes @kimbring2

**Comment by kimbring2** [comment]
@satyamedh Maybe some setting of current your computer is not fit for running Malmo. What type of OS(version) are you using?

**Comment by satyamedh** [comment]
I use win 10. I think because I use a conda Virtual environment, the java_home variable was not passed to the VE. I will set it and see what happenes

**Comment by satyamedh** [comment]
@kimbring2

**Comment by satyamedh** [comment]
> @satyamedh Maybe some setting of current your computer is not fit for running Malmo. What type of OS(version) are you using?

I know I have a low end gpu(gt 710), but I have scaled down the training enough for it to run on 4 gigs of ram

**Comment by kimbring2** [comment]
@satyamedh Oh, I did not mean about GPU. I said about your JAVA setting. Try it without Conda virtual envirinment.

I wish it will run well.

**Comment by satyamedh** [comment]
@kimbring2 , I guess I give up with reinforcement learning.
I will try deep Q learning
thx anyway

**Comment by kimbring2** [comment]
@satyamedh Try it using more simple platform like a OpenAI gym. Malmo is little intermediate.

**Comment by satyamedh** [comment]
@kimbring2 , I know
I am telling u after I made a model that defeats most openai gyms

**Comment by satyamedh** [comment]
Hey @kimbring2 , Guess what? 
.
.
.
.
.
.
.
.
java_home was pointing to a jre LOL
so fixed that!
yet to test the code again!
THX FOR THIS CODE THO!!!!

**Comment by satyamedh** [comment]
ooops

**Comment by satyamedh** [comment]
the code still dosent work @kimbring2
